import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { isAuthenticated } from "@/lib/utils/auth";
import { logoutAction } from "@/lib/authActions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const loggedIn = await isAuthenticated();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <nav>
          {loggedIn ? (
            // user is logged in: show logout button
            <form action={logoutAction}>
              <button type="submit">Logout</button>
            </form>
          ) : (
            // user is not logged in: show login and register links
            <>
              <a href="/auth/login">Login</a>
              <a href="/auth/register">Register</a>
            </>
          )}
        </nav>
        {children}
      </body>
    </html>
  );
}
